server:
  port: 8966
spring:
  application:
    name: ice-auth
  cloud:
    consul:
      discovery:
        serviceName: authorization
      host: localhost
      port: 8500
  profiles:
    active: dev
  datasource:
    name: ice-user
    url: jdbc:mysql://localhost:3306/ice-authorization?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      query-timeout: 2400
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml
  typeAliasesPackage: com.ice.auth.*.domain.po
  global-config:
    refresh: true
    db-config:
      field-strategy: NOT_EMPTY
      id-type: AUTO
      db-type: MYSQL
      column-like: false
      capital-mode: false
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
logging:
  config: classpath:spring-logback.xml